# Simple Makefile for running a hot server with
# parceljs bundler and flask as backend

SERVER_BASE=./server

run-dev:
	ag -l | entr make build

build:
	# use parcel to bundle assets
	parcel build src/index.html --public-url ./ 
	# copy index to templates
	#rm $(SERVER_BASE)/templates/index.html
	cp dist/index.html $(SERVER_BASE)/app/templates
	# copy other files generated by parcel to code assets dir
	#rm $(SERVER_BASE)/app/code/*
	find dist/ -type f ! -name index.html -exec cp -t $(SERVER_BASE)/app/code/ {} +

run:
	# run flask with hot reloading
	cd $(SERVER_BASE)
	flask run --reload --port 5000 &

clean:
	rm $(SERVER_BASE)/app/code/*

