# Simple Makefile for running a hot server with
# parceljs bundler and flask as backend

# Comments on Makefile syntax
# @ - suppress print output
# \ - line break; lines in Makefiles are run in different bash subshells
# 	so it's not possible to do complex scripting without using line break
#	effectively a single-line script
# # unindented comments - comments which are indented inside a target
# 	are echoed

SERVER_BASE=./server
PORT=8089

# start hotloading server.
run-dev: start-dev-server
	i3-msg split h
	code &
	sleep 1
	i3-msg focus left
	i3-msg split v
	gnome-terminal -- bash -c 'ag -l | entr make build'

start-dev-server:
# verify if version of flask supports multifile watching
	@if [ $(shell flask --version | grep "Flask" | sed 's/[^0-9]*//g') -lt 11 ]; \
	then \
		echo 'Version of flask is probably too low; are you using 1.1-dev?'; \
		echo 'Not launching flask...'; \
	else \
		# flask hotwatch; \
		export FLASK_RUN_EXTRA_FILES=$(echo app/*/* | tr " " ":"); \
		export FLASK_APP=$(SERVER_BASE)/app; \
		export FLASK_ENV=development; \
		flask run --port $(PORT) & \
	fi
	
build:
# use parcel to bundle assets
	@parcel build src/index.html --public-url ./ 
# copy index to templates
#-rm $(SERVER_BASE)/app/templates/index.html
	@cp dist/index.html $(SERVER_BASE)/app/templates/index.html
# copy other files generated by parcel to code assets dir
#-rm $(SERVER_BASE)/app/code/*
	@find dist/ -type f ! -name index.html -exec cp -t $(SERVER_BASE)/app/code/ {} +

run:
	# run flask with hot reloading
	cd $(SERVER_BASE)
	flask run --reload --port 5000 &

clean:
	rm $(SERVER_BASE)/app/code/*

